from Helper import Helper
from AddressingEnum import *
from OperationEnum import *


class OpCodeLookup:
    lookupTable = dict()

    # low byte 0
    lookupTable.update({Helper.get_decimal_number_from_hex_string("00"): (OperationEnum.BRK, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("10"): (OperationEnum.BPL, AddressingEnum.rel)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("20"): (OperationEnum.JSR, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("30"): (OperationEnum.BMI, AddressingEnum.rel)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("40"): (OperationEnum.RTI, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("50"): (OperationEnum.BVC, AddressingEnum.rel)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("60"): (OperationEnum.RTS, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("70"): (OperationEnum.BVS, AddressingEnum.rel)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("90"): (OperationEnum.BCC, AddressingEnum.rel)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("A0"): (OperationEnum.LDY, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("B0"): (OperationEnum.BCS, AddressingEnum.rel)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("C0"): (OperationEnum.CPY, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("D0"): (OperationEnum.BNE, AddressingEnum.rel)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("E0"): (OperationEnum.CPX, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("F0"): (OperationEnum.BEQ, AddressingEnum.rel)})

    # low byte 1
    lookupTable.update({Helper.get_decimal_number_from_hex_string("01"): (OperationEnum.ORA, AddressingEnum.xInd)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("11"): (OperationEnum.ORA, AddressingEnum.indY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("21"): (OperationEnum.AND, AddressingEnum.xInd)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("31"): (OperationEnum.AND, AddressingEnum.indY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("41"): (OperationEnum.EOR, AddressingEnum.xInd)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("51"): (OperationEnum.EOR, AddressingEnum.indY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("61"): (OperationEnum.ADC, AddressingEnum.xInd)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("71"): (OperationEnum.ADC, AddressingEnum.indY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("81"): (OperationEnum.STA, AddressingEnum.xInd)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("91"): (OperationEnum.STA, AddressingEnum.indY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("A1"): (OperationEnum.LDA, AddressingEnum.xInd)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("B1"): (OperationEnum.LDA, AddressingEnum.indY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("C1"): (OperationEnum.CMP, AddressingEnum.xInd)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("D1"): (OperationEnum.CMP, AddressingEnum.indY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("E1"): (OperationEnum.SBC, AddressingEnum.xInd)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("F1"): (OperationEnum.SBC, AddressingEnum.indY)})

    # low byte 2
    lookupTable.update({Helper.get_decimal_number_from_hex_string("A2"): (OperationEnum.LDX, AddressingEnum.imm)})

    # low byte 4
    lookupTable.update({Helper.get_decimal_number_from_hex_string("24"): (OperationEnum.BIT, AddressingEnum.zpg)})

    lookupTable.update({Helper.get_decimal_number_from_hex_string("84"): (OperationEnum.STY, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("94"): (OperationEnum.STY, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("A4"): (OperationEnum.LDY, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("B4"): (OperationEnum.LDY, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("C4"): (OperationEnum.CPY, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("E4"): (OperationEnum.CPX, AddressingEnum.zpg)})

    # low byte 5
    lookupTable.update({Helper.get_decimal_number_from_hex_string("05"): (OperationEnum.ORA, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("15"): (OperationEnum.ORA, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("25"): (OperationEnum.AND, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("35"): (OperationEnum.AND, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("45"): (OperationEnum.EOR, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("55"): (OperationEnum.EOR, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("65"): (OperationEnum.ADC, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("75"): (OperationEnum.ADC, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("85"): (OperationEnum.STA, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("95"): (OperationEnum.STA, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("A5"): (OperationEnum.LDA, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("B5"): (OperationEnum.LDA, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("C5"): (OperationEnum.CMP, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("D5"): (OperationEnum.CMP, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("E5"): (OperationEnum.SBC, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("F5"): (OperationEnum.SBC, AddressingEnum.zpgX)})

    # low byte 6
    lookupTable.update({Helper.get_decimal_number_from_hex_string("06"): (OperationEnum.ASL, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("16"): (OperationEnum.ASL, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("26"): (OperationEnum.ROL, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("36"): (OperationEnum.ROL, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("46"): (OperationEnum.LSR, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("56"): (OperationEnum.LSR, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("66"): (OperationEnum.ROR, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("76"): (OperationEnum.ROR, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("86"): (OperationEnum.STX, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("96"): (OperationEnum.STX, AddressingEnum.zpgY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("A6"): (OperationEnum.LDX, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("B6"): (OperationEnum.LDX, AddressingEnum.zpgY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("C6"): (OperationEnum.DEC, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("D6"): (OperationEnum.DEC, AddressingEnum.zpgX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("E6"): (OperationEnum.INC, AddressingEnum.zpg)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("F6"): (OperationEnum.INC, AddressingEnum.zpgX)})

    # low byte 8
    lookupTable.update({Helper.get_decimal_number_from_hex_string("08"): (OperationEnum.PHP, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("18"): (OperationEnum.CLC, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("28"): (OperationEnum.PLP, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("38"): (OperationEnum.SEC, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("48"): (OperationEnum.PHA, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("58"): (OperationEnum.CLI, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("68"): (OperationEnum.PLA, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("78"): (OperationEnum.SEI, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("88"): (OperationEnum.DEY, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("98"): (OperationEnum.TYA, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("A8"): (OperationEnum.TAY, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("B8"): (OperationEnum.CLV, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("C8"): (OperationEnum.INY, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("D8"): (OperationEnum.CLD, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("E8"): (OperationEnum.INX, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("F8"): (OperationEnum.SED, AddressingEnum.impl)})

    # low byte 9
    lookupTable.update({Helper.get_decimal_number_from_hex_string("09"): (OperationEnum.ORA, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("19"): (OperationEnum.ORA, AddressingEnum.absY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("29"): (OperationEnum.AND, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("39"): (OperationEnum.AND, AddressingEnum.absY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("49"): (OperationEnum.EOR, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("59"): (OperationEnum.EOR, AddressingEnum.absY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("69"): (OperationEnum.ADC, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("79"): (OperationEnum.ADC, AddressingEnum.absY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("99"): (OperationEnum.STA, AddressingEnum.absY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("A9"): (OperationEnum.LDA, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("B9"): (OperationEnum.LDA, AddressingEnum.absY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("C9"): (OperationEnum.CMP, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("D9"): (OperationEnum.CMP, AddressingEnum.absY)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("E9"): (OperationEnum.SBC, AddressingEnum.imm)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("F9"): (OperationEnum.SBC, AddressingEnum.absY)})

    # low byte A
    lookupTable.update({Helper.get_decimal_number_from_hex_string("0A"): (OperationEnum.ASL, AddressingEnum.A)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("2A"): (OperationEnum.ROL, AddressingEnum.A)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("4A"): (OperationEnum.LSR, AddressingEnum.A)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("6A"): (OperationEnum.ROR, AddressingEnum.A)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("8A"): (OperationEnum.TXA, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("9A"): (OperationEnum.TXS, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("AA"): (OperationEnum.TAX, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("BA"): (OperationEnum.TSX, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("CA"): (OperationEnum.DEX, AddressingEnum.impl)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("EA"): (OperationEnum.NOP, AddressingEnum.impl)})

    # low byte C
    lookupTable.update({Helper.get_decimal_number_from_hex_string("2C"): (OperationEnum.BIT, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("4C"): (OperationEnum.JMP, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("6C"): (OperationEnum.JMP, AddressingEnum.ind)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("8C"): (OperationEnum.STY, AddressingEnum.ind)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("AC"): (OperationEnum.LDY, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("BC"): (OperationEnum.LDY, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("CC"): (OperationEnum.CPY, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("EC"): (OperationEnum.CPX, AddressingEnum.abs)})

    # low byte D
    lookupTable.update({Helper.get_decimal_number_from_hex_string("0D"): (OperationEnum.ORA, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("1D"): (OperationEnum.ORA, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("2D"): (OperationEnum.AND, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("3D"): (OperationEnum.AND, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("4D"): (OperationEnum.EOR, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("5D"): (OperationEnum.EOR, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("6D"): (OperationEnum.ADC, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("7D"): (OperationEnum.ADC, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("8D"): (OperationEnum.STA, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("9D"): (OperationEnum.STA, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("AD"): (OperationEnum.LDA, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("BD"): (OperationEnum.LDA, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("CD"): (OperationEnum.CMP, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("DD"): (OperationEnum.CMP, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("ED"): (OperationEnum.SBC, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("FD"): (OperationEnum.SBC, AddressingEnum.absX)})

    # low byte E
    lookupTable.update({Helper.get_decimal_number_from_hex_string("0E"): (OperationEnum.ASL, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("1E"): (OperationEnum.ASL, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("2D"): (OperationEnum.ROL, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("3D"): (OperationEnum.ROL, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("4D"): (OperationEnum.LSR, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("5D"): (OperationEnum.LSR, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("6D"): (OperationEnum.ROR, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("7D"): (OperationEnum.ROR, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("8D"): (OperationEnum.STX, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("AD"): (OperationEnum.LDX, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("BD"): (OperationEnum.LDX, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("CD"): (OperationEnum.DEC, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("DD"): (OperationEnum.DEC, AddressingEnum.absX)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("ED"): (OperationEnum.INC, AddressingEnum.abs)})
    lookupTable.update({Helper.get_decimal_number_from_hex_string("FD"): (OperationEnum.INC, AddressingEnum.absX)})
